# Generated by Django 4.2.3 on 2023-07-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fullname',
            field=models.TextField(blank=True),
        ),
    ]
