# Generated by Django 4.2.3 on 2023-07-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fullname',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
