# Generated by Django 4.2.3 on 2023-07-16 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_followerscount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.AddField(
            model_name='post',
            name='Post',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
